# This file was generated by GoReleaser. DO NOT EDIT.
cask "griffino" do
  version "0.0.1-dev"

  on_macos do
    on_intel do
      sha256 "8e1046d146805afc4d62b9cdbf95c17cf133cc37560cd2a5b7025fd30c68ff92"
      url "https://github.com/GriffinGuard/Griffino/releases/download/v#{version}/griffino_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2dcafbc4a8887ef6e6c7e4dbf8a0807b22a27507c8388c01f88997dbae61ad72"
      url "https://github.com/GriffinGuard/Griffino/releases/download/v#{version}/griffino_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "68f63e98644b6c16223141c2f299862b1a961e98b7e342eb78e13a87e2c9cc36"
      url "https://github.com/GriffinGuard/Griffino/releases/download/v#{version}/griffino_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "77ff81b75ea4f0ddf1acab1138f40ce393ffe8192c74887d62224b554293aed9"
      url "https://github.com/GriffinGuard/Griffino/releases/download/v#{version}/griffino_#{version}_linux_arm64.tar.gz"
    end
  end

  name "griffino"
  desc "Plugin orchestration platform with message-driven containers."
  homepage "https://github.com/GriffinGuard/Griffino"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "griffino"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/griffino"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Griffino's daemon runs RabbitMQ and Redis as Docker containers, so Docker
    must be installed and running before `griffino daemon`:
      - Docker Desktop:  brew install --cask docker
      - or colima:       brew install colima docker && colima start
    With colima, export DOCKER_HOST=unix://$HOME/.colima/default/docker.sock
  EOS
end
