# This file was generated by GoReleaser. DO NOT EDIT.
cask "griffino" do
  version "0.0.2-dev"

  on_macos do
    on_intel do
      sha256 "f74616875bb5941c8567f915ba9a4bc7efbf38d153bdef4779ce95fcc71c1ddc"
      url "https://github.com/GriffinGuard/Griffino/releases/download/v#{version}/griffino_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "359a1120e88e58ef62c98cdf2651d4f39afecb974507f23aea01b2754b4c04fa"
      url "https://github.com/GriffinGuard/Griffino/releases/download/v#{version}/griffino_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "18584c6a0f5018427dc6a00cdd8cfe2b7d5495b3defdfd8c445bcee5c44a3cf1"
      url "https://github.com/GriffinGuard/Griffino/releases/download/v#{version}/griffino_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a200d29e73ec5d35d112953155fbad986a18fb613c6278ec505f550205e0e7b1"
      url "https://github.com/GriffinGuard/Griffino/releases/download/v#{version}/griffino_#{version}_linux_arm64.tar.gz"
    end
  end

  name "griffino"
  desc "Plugin orchestration platform with message-driven containers."
  homepage "https://github.com/GriffinGuard/Griffino"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "griffino"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/griffino"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Griffino's daemon runs RabbitMQ and Redis as Docker containers, so Docker
    must be installed and running before `griffino daemon`:
      - Docker Desktop:  brew install --cask docker
      - or colima:       brew install colima docker && colima start
    With colima, export DOCKER_HOST=unix://$HOME/.colima/default/docker.sock
  EOS
end
